# Numpy basics

### 1 Create Array

In [1]:
import numpy as np

In [2]:
# From Python list
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [4]:
# 2D Array
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


## Tensor

In [4]:
np.array([[[1,2,3], [4,5,6]],
          [[7,8,9],[10,11,12]],
          [[13,14,15],[16,17,18]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [6]:
# with zeros
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# With zeros
arr3 = np.zeros((3, 3))
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
# with one
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
arr4 = np.ones((3, 5))
print(arr4)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
# Range of numbers
np.arange(0, 10, 2)  # start, stop, step

array([0, 2, 4, 6, 8])

In [11]:
arr5 = np.arange(0, 10, 2)  # start, stop, step
print(arr5)

[0 2 4 6 8]


In [12]:
# evenly values
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
arr6 = np.linspace(0, 1, 5)  # 5 values between 0 and 1
print(arr6)

[0.   0.25 0.5  0.75 1.  ]


In [14]:
# Identity matrix
arr7 = np.eye(3)
print(arr7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
np.full((3,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [15]:
arr8 = np.random.rand(2, 3)  # uniform distribution
for i in arr8:
    print([i*100])

[array([84.89683813, 35.20862627, 38.16465153])]
[array([87.26659051, 30.97939871, 58.92027171])]


In [16]:
# Random numbers
arr8 = np.random.rand(2, 3)  # uniform distribution
print(arr8)

[[0.73341669 0.8447039  0.96155054]
 [0.08141118 0.45684738 0.14122383]]


In [17]:
arr9 = np.random.randn(3, 3)  # normal distribution
print(arr9)

[[ 0.33798123 -2.38216217  0.39590469]
 [-0.11549112 -0.10739083  1.00338206]
 [-0.25126305  1.090437    0.55624329]]


In [18]:
arr10 = np.random.randint(1, 100, 5)  # random integers
print(arr10)

[91 15 18 67 49]


In [19]:
# Generate 2D random integers (say 3 rows, 4 columns)
arr2d = np.random.randint(1, 100, (3, 4))
print(arr2d)

[[12 52 54  7]
 [95 41 28 36]
 [12 16  8 64]]


In [20]:
# Extra Numpy
arr10 = np.random.randint(1, 100, 5)
print("1D Array:", arr10)

# Convert to 2D (row vector)
arr2d_row = arr10.reshape(1, 5)
print("Row vector:\n", arr2d_row)

# Convert to 2D (column vector)
arr2d_col = arr10.reshape(5, 1)
print("Column vector:\n", arr2d_col)


1D Array: [34 98 55 80 35]
Row vector:
 [[34 98 55 80 35]]
Column vector:
 [[34]
 [98]
 [55]
 [80]
 [35]]


# Array Properties

In [21]:
arr = np.array([[1,2,3],[4,5,6]])

In [22]:
print(arr.ndim)      # dimensions

2


In [23]:
print(arr.shape)     # rows and cols

(2, 3)


In [24]:
print(arr.size)      # total elements

6


In [25]:
print(arr.dtype)     # datatype

int64


In [26]:
print(arr.itemsize)  # size of each element in bytes

8
