# Array Indexxing & Slicing

# 1-D slicing

In [1]:
import numpy as np

In [2]:
arr = np.array([10,20,30,40,50])

In [3]:
print(arr[0])   # first element

10


In [4]:
print(arr[-1])  # last element

50


In [5]:
print(arr[1:4]) # slice

[20 30 40]


In [6]:
print(arr[:3])  # first 3

[10 20 30]


In [7]:
print(arr[-2])

40


In [8]:
print(arr[::2]) # every 2nd element

[10 30 50]


# 2-D Slicing

In [3]:
# 2D slicing
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2[0, 1])    # element at row0 col1

2


In [12]:
print(arr2[2,2])

9


In [13]:
print(arr2[1:, :2])  # submatrix

[[4 5]
 [7 8]]


In [14]:
print(arr2[1:2, 1:2])

[[5]]


In [15]:
print(arr2[1])

[4 5 6]


In [17]:
print(arr2[:,1])

[2 5 8]


In [18]:
print(arr2[:1])

[[1 2 3]]


In [4]:
print(arr2[:2,1:2])

[[2]
 [5]]
