# Arithmetic Operation

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [3]:
print(a + b)

[5 7 9]


In [4]:
print(a - b)

[-3 -3 -3]


In [5]:
print(b-a)

[3 3 3]


In [6]:
print(a * b)

[ 4 10 18]


In [7]:
print(a / b)

[0.25 0.4  0.5 ]


In [8]:
print(a ** b)

[  1  32 729]
