# Universal Function

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
print(np.sqrt(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [4]:
print(np.exp(arr))  #exponential function 

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [5]:
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [6]:
print(np.sin(arr))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [7]:
print(np.cos(arr))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [8]:
print(np.max(arr))

5


In [9]:
print(np.min(arr))

1


In [10]:
print(np.sum(arr))

15


In [11]:
print(np.mean(arr))

3.0


In [12]:
print(np.median(arr))

3.0


In [13]:
print(np.std(arr))   # standard deviation

1.4142135623730951
