# Vstack
## Add New Columns in the array

In [2]:
import numpy as np

In [3]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [4]:
# Horizontal stack and add new columns
print(np.hstack((a,b)))

[[1 2 5 6]
 [3 4 7 8]]


In [5]:
# Vertical stack  add new row in it
print(np.vstack((a,b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [5]:
# Concatenate
print(np.concatenate((a,b), axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [6]:
# Split
arr = np.arange(10)
print(np.split(arr, 2))

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


In [7]:
# Split
arr = np.arange(12)
print(np.split(arr, 4))

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]


In [8]:
# Split
arr = np.arange(20)
print(np.split(arr, 4))

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14]), array([15, 16, 17, 18, 19])]


In [6]:
original = np.array([[1,2], [3,4]])
new_rows = np.array([[5,6]])

In [8]:
with_new_row= np.vstack((original, new_rows))
print(original)
print(with_new_row)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]


In [10]:
original = np.array([[1,2], [3,4]])
new_rows = np.array([[5],[6]])

In [11]:
with_new_column= np.hstack((original, new_rows))
print(original)
print(with_new_column)

[[1 2]
 [3 4]]
[[1 2 5]
 [3 4 6]]


In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr1 = np.split(arr, 5)
print(arr1)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]


In [3]:
print(np.split(arr,2))

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]


In [5]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

new_arr = np.concatenate((arr1, arr2))
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
print(np.hsplit(arr,2))

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]


In [7]:
print(np.split(arr,5))

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]
