# BroadCasting

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = 2
print(a + b)   # [3 4 5]

[3 4 5]


In [3]:
matrix = np.ones((3,3))
vec = np.array([1,2,3])
print(matrix + vec)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [4]:
matrix = np.ones((3,3))
print(matrix)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
vec = np.array([1,2,3])
print(vec)

[1 2 3]


In [6]:
matrix = np.array([[1,2,3],[4,5,6]])
vector = np.array([10,20,30])
result = matrix + vector
print(result)

[[11 22 33]
 [14 25 36]]


In [7]:
print(matrix * vector)

[[ 10  40  90]
 [ 40 100 180]]
