# BroadCasting

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = 2
print(a + b)   # [3 4 5]

[3 4 5]


In [3]:
matrix = np.ones((3,3))
vec = np.array([1,2,3])
print(matrix + vec)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [4]:
matrix = np.ones((3,3))
print(matrix)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
vec = np.array([1,2,3])
print(vec)

[1 2 3]
