# Random Module

In [1]:
import numpy as np

In [2]:
print(np.random.rand(3))

[0.51548152 0.59848193 0.91827864]


In [3]:
print(np.random.rand(3,6))

[[0.1352447  0.05930482 0.27539637 0.27918668 0.20532059 0.83063036]
 [0.07347653 0.78678792 0.40439035 0.32152713 0.40961899 0.65234705]
 [0.12017544 0.72130054 0.18798094 0.13231683 0.49997217 0.18238671]]


In [4]:
print(np.random.randint(1,10))

8


In [5]:
print(np.random.choice([1,2,3,4,5]))

1


In [6]:
dt = np.random.seed(42)  

In [7]:
print(np.random.rand(3))

[0.37454012 0.95071431 0.73199394]


In [8]:
print(np.random.rand(3))

[0.59865848 0.15601864 0.15599452]
