# Random Module

In [1]:
import numpy as np

In [2]:
print(np.random.rand(3))

[0.05219671 0.97880842 0.2415865 ]


In [7]:
print(np.random.rand(3,6))

[[0.14162423 0.34462901 0.53767163 0.23948709 0.04880575 0.31771641]
 [0.35199275 0.37557647 0.94671935 0.99158016 0.81656606 0.72591789]
 [0.68743704 0.54827526 0.02752336 0.79354727 0.22894964 0.57110126]]


In [8]:
print(np.random.randint(1,10))

3


In [9]:
print(np.random.choice([1,2,3,4,5]))

2


In [10]:
dt = np.random.seed(42)  