# Practice time

In [2]:
# find even number
arr = np.arange(1, 21)
evens = arr[arr % 2 == 0]
print(evens)

[ 2  4  6  8 10 12 14 16 18 20]


In [1]:
import numpy as np

In [3]:
# find odd numbers replace with -1
arr = np.arange(10)
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [4]:
# sort array
arr = np.array([5,3,8,1,2])
print(np.sort(arr))

[1 2 3 5 8]


In [5]:
# unique element
arr = np.array([1,2,2,3,4,4,5])
print(np.unique(arr))

[1 2 3 4 5]


In [6]:
# matirx multiplication
A = np.array([[1,2],[3,4]])
B = np.array([[2,0],[1,2]])
print(np.dot(A,B))

[[ 4  4]
 [10  8]]


In [7]:
# find max and index
arr = np.array([10,20,5,40,30])
print(np.max(arr))
print(np.argmax(arr))  # index of max

40
3


In [8]:
# convert the 1D to 2D columns matrix
arr = np.arange(6)
print(arr.reshape(-1,1))

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [9]:
# sum along rows and columns
arr = np.array([[1,2,3],[4,5,6]])
print(np.sum(arr, axis=0))  # column sum
print(np.sum(arr, axis=1))  # row sum

[5 7 9]
[ 6 15]


In [10]:
# generate identity matrix
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
# check the memory usage
arr = np.arange(1000)
print(arr.nbytes)

8000


## More Practice

In [12]:
# From Python list
arr = np.array([1, 2, 3, 4])
print(arr)

# Multidimensional array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

# Array of zeros
zeros = np.zeros((3, 3))

# Array of ones
ones = np.ones((2, 4))

# Identity matrix
eye = np.eye(4)

# Array with range
range_arr = np.arange(0, 10, 2)   # like range(), but returns array

# Evenly spaced numbers
linspace_arr = np.linspace(0, 1, 5)  # 5 numbers between 0 and 1
eye
ones
zeros
arr2d
range_arr
linspace_arr

[1 2 3 4]


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
range_arr

array([0, 2, 4, 6, 8])

In [18]:
linspace_arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [20]:
# Stacking
print(np.vstack((a,b)))  # vertical stack
print(np.hstack((a,b)))  # horizontal stack

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [21]:
# Compute row-wise normalization
data = np.array([[1,2,3],[4,5,6]])

row_sum = data.sum(axis=1).reshape(-1,1)
normalized = data / row_sum

print(normalized)

[[0.16666667 0.33333333 0.5       ]
 [0.26666667 0.33333333 0.4       ]]
