## Fancy Indexing vs np.where()

In [2]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])

In [1]:
import numpy as np

In [3]:
indices = [0,2,4]
print(numbers[indices])

[1 3 5]


In [5]:
where_result = np.where(numbers>5)
print(where_result)
print("NP where ",numbers[where_result])

(array([5, 6, 7, 8, 9]),)
NP where  [ 6  7  8  9 10]


In [7]:
condition_array = np.where(numbers>5, numbers*4,numbers)
print(condition_array)

[ 1  2  3  4  5 24 28 32 36 40]


In [8]:
condition_array = np.where(numbers>5, "true","false")
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']
