## Deletion of elements 

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,44,6])
deleted = np.delete(arr, 3)
print("After delete :",deleted)

After delete : [1 2 3 6]


In [4]:
arr2 = np.array([[1,3,5,7],[2,4,6,8],[3,6,9,12]])
deleted = np.delete(arr2, [(1,2)])
print(deleted)

[ 1  7  2  4  6  8  3  6  9 12]


In [5]:
# array index value
print(np.insert(arr, 2, 50, axis=None))

[ 1  2 50  3 44  6]


In [7]:
print(np.insert(arr2, 1, [5,6], axis=None))

[ 1  5  6  3  5  7  2  4  6  8  3  6  9 12]


In [9]:
print(np.append(arr, 100))

[  1   2   3  44   6 100]
