# NumPy — Complete Guide & Examples

**What you'll find:** a step-by-step NumPy tutorial with runnable code cells covering arrays, indexing, operations, universal functions, reshaping, broadcasting, linear algebra, random, and many useful programs.

**How to use:** download this notebook, open it in JupyterLab / Jupyter Notebook / VS Code, and run cells one-by-one.


In [1]:
# If NumPy is not installed, uncomment and run the following line:
# !pip install numpy

import numpy as np
import math

print('NumPy version:', np.__version__)

NumPy version: 2.2.3


## 1) Creating Arrays

Examples: from lists, zeros, ones, arange, linspace, identity, random.

In [2]:
# Creating arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
zeros = np.zeros((3,3))
ones = np.ones((2,4))
arr_range = np.arange(0, 10, 2)
arr_lin = np.linspace(0, 1, 5)
identity = np.eye(3)
rand_uniform = np.random.rand(2,3)
rand_normal = np.random.randn(3,3)
rand_int = np.random.randint(1, 100, (3,4))

arr1, arr2, zeros, ones, arr_range, arr_lin, identity, rand_uniform, rand_normal, rand_int

(array([1, 2, 3, 4, 5]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([0, 2, 4, 6, 8]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[0.56991457, 0.25307373, 0.9818633 ],
        [0.58750902, 0.46801173, 0.58749147]]),
 array([[ 0.87624886,  0.47752716,  0.89168789],
        [ 0.30758797,  0.33183644, -0.61367488],
        [ 0.20826014, -0.82039799, -1.63802031]]),
 array([[44, 35, 99, 36],
        [ 9, 59, 74, 68],
        [98, 14, 87, 75]], dtype=int32))

## 2) Array Properties (ndim, shape, size, dtype, itemsize)

In [3]:
a = np.array([[1,2,3],[4,5,6]])
print('array:\n', a)
print('ndim:', a.ndim)
print('shape:', a.shape)
print('size:', a.size)
print('dtype:', a.dtype)
print('itemsize (bytes):', a.itemsize)

array:
 [[1 2 3]
 [4 5 6]]
ndim: 2
shape: (2, 3)
size: 6
dtype: int64
itemsize (bytes): 8


## 3) Indexing & Slicing

1D and 2D examples.

In [4]:
arr = np.array([10,20,30,40,50])
print('arr[0] =', arr[0])
print('arr[-1] =', arr[-1])
print('arr[1:4] =', arr[1:4])
print('arr[:3] =', arr[:3])
print('arr[::2] =', arr[::2])

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('\narr2:\n', arr2)
print('arr2[0,1] =', arr2[0,1])
print('arr2[1: , :2] =\n', arr2[1: , :2])

arr[0] = 10
arr[-1] = 50
arr[1:4] = [20 30 40]
arr[:3] = [10 20 30]
arr[::2] = [10 30 50]

arr2:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr2[0,1] = 2
arr2[1: , :2] =
 [[4 5]
 [7 8]]


## 4) Operations & Vectorization

Element-wise arithmetic and vectorized math functions.

In [5]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print('a + b =', a + b)
print('a - b =', a - b)
print('a * b =', a * b)
print('a / b =', a / b)
print('a ** 2 =', a ** 2)

arr = np.array([1,2,3,4,5])
print('\nnp.sqrt(arr) =', np.sqrt(arr))
print('np.exp(arr) =', np.exp(arr))
print('np.log(arr) =', np.log(arr))
print('np.sin(arr) =', np.sin(arr))
print('np.cos(arr) =', np.cos(arr))
print('\nmax, min, sum, mean, median, std:')
print(np.max(arr), np.min(arr), np.sum(arr), np.mean(arr), np.median(arr), np.std(arr))

a + b = [5 7 9]
a - b = [-3 -3 -3]
a * b = [ 4 10 18]
a / b = [0.25 0.4  0.5 ]
a ** 2 = [1 4 9]

np.sqrt(arr) = [1.         1.41421356 1.73205081 2.         2.23606798]
np.exp(arr) = [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
np.log(arr) = [0.         0.69314718 1.09861229 1.38629436 1.60943791]
np.sin(arr) = [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
np.cos(arr) = [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]

max, min, sum, mean, median, std:
5 1 15 3.0 3.0 1.4142135623730951


### np.exp vs math.exp

`np.exp` is vectorized (works on arrays). `math.exp` works on scalars only.

In [6]:
import math
arr = np.array([1,2,3,4,5])
print('np.exp(arr) ->', np.exp(arr))
# math.exp applied element-wise using a Python loop
print('math.exp applied with list comprehension ->', [math.exp(x) for x in arr])

# Quick performance demo (short runs to keep it light)
import time
vals = np.random.rand(100)
# time vectorized np.exp on vals repeated 100 times
t0 = time.time()
for _ in range(100):
    _ = np.exp(vals)
t1 = time.time()
# time math.exp in a Python loop
vals_list = vals.tolist()
t2 = time.time()
for _ in range(100):
    _ = [math.exp(x) for x in vals_list]
t3 = time.time()
print('\nElapsed (np.exp 100 runs):', t1-t0)
print('Elapsed (math.exp in loop 100 runs):', t3-t2)
print('\nNote: np.exp is implemented in C and is much faster for array work.')

np.exp(arr) -> [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
math.exp applied with list comprehension -> [2.718281828459045, 7.38905609893065, 20.085536923187668, 54.598150033144236, 148.4131591025766]

Elapsed (np.exp 100 runs): 0.00019860267639160156
Elapsed (math.exp in loop 100 runs): 0.0009248256683349609

Note: np.exp is implemented in C and is much faster for array work.


## 5) Reshaping & Flattening

Use `reshape`, `flatten`, `ravel`, and transpose.

In [7]:
arr = np.arange(12)
print('arr =', arr)
reshaped = arr.reshape(3,4)
print('reshaped 3x4:\n', reshaped)
print('flatten ->', reshaped.flatten())
print('ravel (view) ->', reshaped.ravel())
print('transpose ->\n', reshaped.T)

arr = [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flatten -> [ 0  1  2  3  4  5  6  7  8  9 10 11]
ravel (view) -> [ 0  1  2  3  4  5  6  7  8  9 10 11]
transpose ->
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## 6) Stacking & Splitting

`hstack`, `vstack`, `concatenate`, `split`.

In [8]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print('hstack:\n', np.hstack((a,b)))
print('vstack:\n', np.vstack((a,b)))
print('concatenate axis=0:\n', np.concatenate((a,b), axis=0))

arr = np.arange(10)
print('\nsplit arr into 2 ->', np.split(arr, 2))

hstack:
 [[1 2 5 6]
 [3 4 7 8]]
vstack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
concatenate axis=0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

split arr into 2 -> [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


## 7) Broadcasting

Small arrays automatically expand to match larger arrays when compatible.

In [9]:
matrix = np.ones((3,3))
vec = np.array([1,2,3])
print('matrix + vec ->\n', matrix + vec)

matrix + vec ->
 [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


## 8) Linear Algebra

Matrix multiplication, inverse, determinant, eigenvalues.

In [10]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print('A @ B =\n', A @ B)
print('\nnp.dot(A,B) =\n', np.dot(A,B))
print('\ninv(A) =\n', np.linalg.inv(A))
print('det(A) =', np.linalg.det(A))
print('eig(A) =', np.linalg.eig(A))

A @ B =
 [[19 22]
 [43 50]]

np.dot(A,B) =
 [[19 22]
 [43 50]]

inv(A) =
 [[-2.   1. ]
 [ 1.5 -0.5]]
det(A) = -2.0000000000000004
eig(A) = EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


## 9) Random Numbers

`np.random.rand`, `randn`, `randint`, `choice`, and seeding for reproducibility.

In [11]:
np.random.seed(42)
print('rand:', np.random.rand(3))
print('randn:', np.random.randn(3))
print('randint 2x3:', np.random.randint(1, 100, (2,3)))
print('choice from [1,2,3,4,5]:', np.random.choice([1,2,3,4,5], size=3))

rand: [0.37454012 0.95071431 0.73199394]
randn: [-1.11188012  0.31890218  0.27904129]
randint 2x3: [[24  3 22]
 [53  2 88]]
choice from [1,2,3,4,5]: [4 2 4]


## 10) Useful Programs / Practice

Small tasks to practice NumPy.

In [12]:
# 1. Find even numbers
arr = np.arange(1,21)
evens = arr[arr % 2 == 0]
print('evens ->', evens)

# 2. Replace odd numbers with -1
arr2 = np.arange(10)
arr2[arr2 % 2 == 1] = -1
print('\nreplaced odds ->', arr2)

# 3. Sort array
arr3 = np.array([5,3,8,1,2])
print('\nsorted ->', np.sort(arr3))

# 4. Unique elements
arr4 = np.array([1,2,2,3,4,4,5])
print('\nunique ->', np.unique(arr4))

# 5. Matrix multiplication
A = np.array([[1,2],[3,4]])
B = np.array([[2,0],[1,2]])
print('\nA @ B ->\n', A @ B)

# 6. Find max and index
arr5 = np.array([10,20,5,40,30])
print('\nmax, argmax ->', np.max(arr5), np.argmax(arr5))

# 7. Convert 1D to 2D column
arr6 = np.arange(6)
print('\ncolumn vector ->\n', arr6.reshape(-1,1))

# 8. Sum along rows & columns
mat = np.array([[1,2,3],[4,5,6]])
print('\ncol sums:', np.sum(mat, axis=0))
print('row sums:', np.sum(mat, axis=1))

# 9. Identity
print('\nidentity 5:\n', np.eye(5))

# 10. Memory usage
arr_large = np.arange(1000)
print('\narr_large nbytes:', arr_large.nbytes)

evens -> [ 2  4  6  8 10 12 14 16 18 20]

replaced odds -> [ 0 -1  2 -1  4 -1  6 -1  8 -1]

sorted -> [1 2 3 5 8]

unique -> [1 2 3 4 5]

A @ B ->
 [[ 4  4]
 [10  8]]

max, argmax -> 40 3

column vector ->
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]]

col sums: [5 7 9]
row sums: [ 6 15]

identity 5:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

arr_large nbytes: 8000


### Bonus: Convert an existing 1D random integer array into 2D shapes

You can reshape only when total elements match the target shape. Examples below:

In [13]:
arr10 = np.random.randint(1, 100, 5)
print('1D arr10:', arr10)

# row (1 x 5)
row = arr10.reshape(1,5)
print('\nrow (1,5):\n', row)

# column (5 x 1)
col = arr10.reshape(5,1)
print('\ncolumn (5,1):\n', col)

# if you want a different shape, total elements must match the target shape
# e.g., to reshape to (2,3) you must have 6 elements
arr6 = np.random.randint(1,100,6)
print('\narr6 (6 elems):', arr6)
print('reshaped to (2,3):\n', arr6.reshape(2,3))

1D arr10: [21 33 76 58 22]

row (1,5):
 [[21 33 76 58 22]]

column (5,1):
 [[21]
 [33]
 [76]
 [58]
 [22]]

arr6 (6 elems): [89 49 91 59 42 92]
reshaped to (2,3):
 [[89 49 91]
 [59 42 92]]
