# 1 Create Index

In [1]:
import numpy as np
import random

In [2]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
# Create non-repeating values for the index
new_index = np.arange(1,100)

In [9]:
new_index

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [7]:
# Shuffling the indexes

random.shuffle(new_index)

In [5]:
new_index

array([32, 90, 82, 93, 62, 43, 60, 89, 49, 64, 74, 87, 85, 91, 69, 80,  8,
       54, 35, 14, 63, 21, 40, 73, 45, 42, 88,  7, 37, 10, 33, 24, 53, 58,
       22, 98, 50, 79, 47, 68, 16, 59, 77, 44, 96, 31, 30, 36, 81, 97, 67,
       70, 15,  1, 92, 13, 94, 83, 28, 38, 18, 23, 99, 78, 84, 72, 86,  3,
       57,  4, 19, 56, 52, 41, 71,  6, 76, 29, 65,  5, 48, 20,  9, 17, 46,
       75, 39, 11, 26, 95, 61, 12, 51, 27,  2, 34, 66, 55, 25])

In [11]:
import pandas as pd
df =pd.read_csv("students.csv")
df

name  maths  hindi  english gender class
0     a     12     23       56      f  12th
1     b     43     54       88      f   2nd
2     c     54     67       98      f   5th
3     d     55     87       99      m   7th
4     e     34     56       87      m   9th
5     f     65     43       70      f  12th
6     g     66     98       76      m  10th
7     h     98     12       88      m   6th
8     i     65     45       56      m   8th
9     j     55     67       76      f   9th
10    k     45     98       78      m  11th
11    l     98     98       54      f   7th
12    m     67     65       34      m   8th

In [13]:
my_index = np.arange(1,14)
random.shuffle(my_index)
my_index

array([ 6, 10,  5,  8,  1,  9,  4, 13,  7,  3,  2, 12, 11])

In [14]:
df["my_index"]=my_index

In [15]:
df

name  maths  hindi  english gender class  my_index
0     a     12     23       56      f  12th         6
1     b     43     54       88      f   2nd        10
2     c     54     67       98      f   5th         5
3     d     55     87       99      m   7th         8
4     e     34     56       87      m   9th         1
5     f     65     43       70      f  12th         9
6     g     66     98       76      m  10th         4
7     h     98     12       88      m   6th        13
8     i     65     45       56      m   8th         7
9     j     55     67       76      f   9th         3
10    k     45     98       78      m  11th         2
11    l     98     98       54      f   7th        12
12    m     67     65       34      m   8th        11

# 2 Set index

In [16]:
df.set_index('my_index')

name  maths  hindi  english gender class
my_index                                         
6           a     12     23       56      f  12th
10          b     43     54       88      f   2nd
5           c     54     67       98      f   5th
8           d     55     87       99      m   7th
1           e     34     56       87      m   9th
9           f     65     43       70      f  12th
4           g     66     98       76      m  10th
13          h     98     12       88      m   6th
7           i     65     45       56      m   8th
3           j     55     67       76      f   9th
2           k     45     98       78      m  11th
12          l     98     98       54      f   7th
11          m     67     65       34      m   8th

In [17]:
df.set_index('my_index', inplace=True)
df

name  maths  hindi  english gender class
my_index                                         
6           a     12     23       56      f  12th
10          b     43     54       88      f   2nd
5           c     54     67       98      f   5th
8           d     55     87       99      m   7th
1           e     34     56       87      m   9th
9           f     65     43       70      f  12th
4           g     66     98       76      m  10th
13          h     98     12       88      m   6th
7           i     65     45       56      m   8th
3           j     55     67       76      f   9th
2           k     45     98       78      m  11th
12          l     98     98       54      f   7th
11          m     67     65       34      m   8th

# 3 Sort Index

In [19]:
# ascending order
df.sort_index()

name  maths  hindi  english gender class
my_index                                         
1           e     34     56       87      m   9th
2           k     45     98       78      m  11th
3           j     55     67       76      f   9th
4           g     66     98       76      m  10th
5           c     54     67       98      f   5th
6           a     12     23       56      f  12th
7           i     65     45       56      m   8th
8           d     55     87       99      m   7th
9           f     65     43       70      f  12th
10          b     43     54       88      f   2nd
11          m     67     65       34      m   8th
12          l     98     98       54      f   7th
13          h     98     12       88      m   6th

In [20]:
# decreasing order of the index
df.sort_index(ascending=False)

name  maths  hindi  english gender class
my_index                                         
13          h     98     12       88      m   6th
12          l     98     98       54      f   7th
11          m     67     65       34      m   8th
10          b     43     54       88      f   2nd
9           f     65     43       70      f  12th
8           d     55     87       99      m   7th
7           i     65     45       56      m   8th
6           a     12     23       56      f  12th
5           c     54     67       98      f   5th
4           g     66     98       76      m  10th
3           j     55     67       76      f   9th
2           k     45     98       78      m  11th
1           e     34     56       87      m   9th

In [21]:
df.sort_index(ascending=False, inplace=True)

In [22]:
df

name  maths  hindi  english gender class
my_index                                         
13          h     98     12       88      m   6th
12          l     98     98       54      f   7th
11          m     67     65       34      m   8th
10          b     43     54       88      f   2nd
9           f     65     43       70      f  12th
8           d     55     87       99      m   7th
7           i     65     45       56      m   8th
6           a     12     23       56      f  12th
5           c     54     67       98      f   5th
4           g     66     98       76      m  10th
3           j     55     67       76      f   9th
2           k     45     98       78      m  11th
1           e     34     56       87      m   9th