# Array Indexxing & Slicing

In [3]:
import numpy as np

In [4]:
arr = np.array([10,20,30,40,50])

In [5]:
print(arr[0])   # first element

10


In [6]:
print(arr[-1])  # last element

50


In [7]:
print(arr[1:4]) # slice

[20 30 40]


In [8]:
print(arr[:3])  # first 3

[10 20 30]


In [9]:
print(arr[::2]) # every 2nd element

[10 30 50]


# 1-D slicing

# 2-D Slicing

In [10]:
# 2D slicing
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2[0, 1])    # element at row0 col1
print(arr2[1:, :2])  # submatrix

2
[[4 5]
 [7 8]]
