# Reshaping & Flattening

In [1]:
import numpy as np

In [2]:
arr = np.arange(12)
print(arr)

reshaped = arr.reshape(3, 4)
print(reshaped)

flattened = reshaped.flatten()
print(flattened)

# Transpose
print(reshaped.T)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
