# BoardCasting

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = 2
print(a + b)   # [3 4 5]

matrix = np.ones((3,3))
vec = np.array([1,2,3])
print(matrix + vec)

[3 4 5]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
